.MODEL SMALL
.STACK 100H
.DATA
  PROMPT1 DB 10, 13, "Enter a string: $"
  PROMPT2 DB 10, 13, "Enter another string: $"
  PROMPT3 DB 10, 13, "Both strings are equal.$"
  PROMPT4 DB 10, 13, "Both aren't equal.$"
  STR1 DB 100 DUP('$')
  STR2 DB 100 DUP('$')
.CODE
MAIN PROC
  MOV AX, @DATA
  MOV DS, AX ;DATA SEGMENT INITIALIZATION
  MOV ES, AX ;EXTRA SEGMENT INITIALIZATION SO STRING INTRUCTIONS CAN USE ES:DI

  LEA DX, PROMPT1
  MOV AH, 09H
  INT 21H ;DISPLAY PROMPT1

  CLD ;CLEAR DIRECTION FLAG SO ES:DI CAN MOVE FORWARDS
  LEA DI, STR1 ;ES:DI => DI IS POINTING TO STARTING ADDRESS OF STR1
  MOV CX, 99 ;MAX INPUT SIZE 

  INPUT1:
    MOV AH, 01H
    INT 21H ;SINGLE CHARACTER INPUT
    CMP AL, 13D
    JE END_INPUT1 ;JUMP IF RETURN IS ENTERED
    OR AL, 20H ;CONVERTING CHARCATER ENTERED TO UPPERCASE
    STOSB ;MOV CONTENT OF AL TO ES:DI => WHERE DI IS POINTING AND INCREMENTING DI
    LOOP INPUT1 ;CHECK WHETHER CX IS ZERO TO STOP INPUT 

  END_INPUT1:
  LEA DX, PROMPT2
  MOV AH, 09H
  INT 21H ;DISPLAY PROMPT1
  LEA DI, STR2 ;ES:DI => DI IS POINTING TO STARTING ADDRESS OF STR2
  MOV CX, 99 ;MAX INPUT SIZE
  INPUT2:
    MOV AH, 01H
    INT 21H ;SINGLE CHARACTER INPUT
    CMP AL, 13D
    JE END_INPUT2 ;JUMP IF RETURN IS ENTERED
    OR AL, 20H ;CONVERTING CHARCATER ENTERED TO UPPERCASE
    STOSB ;MOV CONTENT OF AL TO ES:DI => WHERE DI IS POINTING AND INCREMENTING DI
    LOOP INPUT2 ;CHECK WHETHER CX IS ZERO TO STOP INPUT

  END_INPUT2:
  LEA SI, STR1 ;DS:SI => SI IS POINTING TO STARTING ADDRESS OF STR1
  LEA DI, STR2 ;ES:DI => DI IS POINTING TO STARTING ADDRESS OF STR2

  MOV CX, 99 ;COUNTER TO REPEAT CMPSB

  REPE CMPSB ;REPEATING COMPARING CONTENT POINTED BY DS:SI TO CONTENT POINTED BY ES:DI CX IS ZERO

  CMP CX, 0 
  JNE NOT_EQUAL ;IF CX IS NOT ZERO IT MEANS COMPARING STR1 AND STR1 STOPED BEACUSE UNEQUAL CHARACTERS WERE ENCOUNTERED
  LEA DX, PROMPT3 
  MOV AH, 09H
  INT 21H ;DISPLAY PROMPT3
  JMP REMAIN

  NOT_EQUAL:
    LEA DX, PROMPT4
    MOV AH, 09H
    INT 21H ;DISPLAY PROMPT4
  
  REMAIN:
  ;EXIT DOS
  MOV AH, 4CH
  INT 21H

MAIN ENDP 
END MAIN
