.MODEL SMALL
.STACK 100H
.DATA
  PROMPT1 DB 10, 13, "Enter a number: $"
  PROMPT2 DB "Factorial of $"
  PROMPT3 DB " is $"
.CODE

INCLUDE Func.asm

MAIN PROC
  MOV AX, @DATA
  MOV DS, AX ;INITIALIZATION OF DATA SEGMENT

  MOV AH, 09H
  LEA DX, PROMPT1
  INT 21H ;DISPLAY PROMPT1 

  CALL DECIMAL_INPUT 
  PUSH AX ;SAVING INPUT

  MOV AH, 09H
  LEA DX, PROMPT2 
  INT 21H ;DISPLAY PROMPT2

  POP AX ;PARAMETER FOR DECIMAL_OUTPUT AX(NUMBER TO DISPLAY)
  CALL DECIMAL_OUTPUT

  PUSH AX ;SAVING INPUT

  MOV AH, 09H
  LEA DX, PROMPT3
  INT 21H ;DISPLAY PROMPT3

  POP CX ;PARAMETER FOR FACTORIAL CX!
  CALL FACTORIAL

  CALL DECIMAL_OUTPUT

  MOV AH, 4CH
  INT 21H ;EXIT DOS 
MAIN ENDP
END MAIN
